name: Dot-Net-Core
on:
  push:
    branches:
      - main
  
jobs:
  CI:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      # Setup ms build
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          msbuild-version: '16.0'
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      # Build the Code using MS Build
      - name: Build with MSBuild
        run: msbuild /p:Configuration=Release
      # Run the Tests
      - name: Test with dotnet test
        run: dotnet test --no-restore --verbosity normal
      # Publish the Code as an artifact to GitHub Releases
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Dot-Net-Core
          path: bin\Release\netcoreapp3.1\publish\